- lib/tcx_builder.py
> [2] fixing calories mapping

- README.md
- lib/tcx_builder.py
> [8] fix invalid file names

- .gitignore
- README.md
- config.ini
- lib/config_helper.py
- lib/garminClient.py
- lib/pelotonApi.py
- lib/tcx_builder.py
- peloton-to-garmin.py
- requirements.txt
WIP - doesn't work yet, just a poc of how to integrate directly with the gupload client.
> [6] initial POC for garmin upload without docker

- lib/tcx_builder.py
- peloton-to-garmin.py
- tests/tcx_test_helper.py
- tests/test_peloton-to-garmin.py
Resistance is not part of the TCX spec but we will try and capture it anyway so the data is preserved.  Garmin Connect will not do anything with data, but it will be present in the original TCX file generated by this script.
Also fixed a bug where the PauseOnFinish config option was not honored.
> Issue 40 - Add Resistance to TCX

- tests/test_tcx_builder.py
> Fix Workout Title bug

- lib/tcx_builder.py
- requirements.txt
- tests/test_tcx_builder.py
> [51] fix accented characters in file name not uploading workout

- lib/pelotonApi.py
> [67] update to new peloton api url

- README.md
- lib/configuration.py
So the script can better run in a docker container, adding support for environment variables.
> Adding ENV Support

- README.md
- config.ini
- lib/configuration.py
- peloton-to-garmin.py
#65 To help out those maintaining docker containers, adding official (and extremely basic) support for polling.  At this time I don't think we need anything fancier than this, so keeping it simple.
> [65] add very basic polling support to help docker folks

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- lib/config_helper.py
This enables to have a local 'config.local.ini' file - which is never be checked in (gitignore).
Just helps for easier development.
> Enables a local config.ini file

- .github/workflows/pr-test.yml
- .github/workflows/publish_distros_latest.yml
- .github/workflows/tag-release.yml
- configuration.example.json
- src/Common/Configuration.cs
- src/PelotonToGarminConsole/PelotonToGarminConsole.csproj
- src/PelotonToGarminConsole/Program.cs
> [140] add setting for CloseWindowOnFinish

- src/Peloton/ApiClient.cs
- src/Peloton/PelotonService.cs
> [160] add paging support when fetching recent workouts from Peloton

- UnitTests/AdHocTests.cs
- UnitTests/Common/Dto/MetricTests.cs
- src/Common/Dto/Metric.cs
- src/Conversion/IConverter.cs
> [179] better handling of null in peloton metrics

- docs/configuration/json.md
- src/Common/Configuration.cs
- src/Common/Database/DbClient.cs
- src/Common/Dto/Metric.cs
- src/Common/Dto/Unit.cs
- src/Conversion/FitConverter.cs
- src/Conversion/IConverter.cs
- src/WebApp/Views/Settings/Index.cshtml
> [177] Support configurable Lap strategies

- UnitTests/Sync/SyncServiceTests.cs
- src/Common/FileHandling.cs
- src/Conversion/IConverter.cs
- src/Peloton/PelotonService.cs
- src/PelotonToGarminConsole/Startup.cs
- src/Sync/SyncService.cs
- src/WebApp/Services/BackgroundSyncJob.cs
closes #220 
Changes are generally done, but I still need to actually test them out.
> [220] Cleanup files after successful run

- UnitTests/Conversion/FitConverterTests.cs
- src/Common/Dto/GarminDeviceInfo.cs
- src/Conversion/FitConverter.cs
> [218] set minor version for device info

- docs/observability.md
I have officially attempted to contribute a single letter
> i R helping

- .github/workflows/pr-test.yml
- Dockerfile
- UnitTests/Common/ConfigurationTests.cs
- docs/install/docker.md
- entrypoint.sh
- src/Common/Configuration.cs
- src/PelotonToGarminConsole/PelotonToGarminConsole.csproj
- src/PelotonToGarminConsole/PelotonToGarminConsole.csproj.user
- src/WebApp/WebApp.csproj
> [230] add default user to Dockerfile

- src/Conversion/IConverter.cs
> [254] fix DirectoryNotFoundException for working directory

- .github/workflows/pr-test.yml
- src/Common/Common.csproj
- src/Conversion/Conversion.csproj
- src/Garmin/Garmin.csproj
- src/Peloton/Peloton.csproj
- src/PelotonToGarminConsole/PelotonToGarminConsole.csproj
- src/Sync/Sync.csproj
- src/WebUI/Pages/Index.razor
> [200] uplift to dotnet 6

- .github/workflows/publish_distros_latest.yml
- .github/workflows/tag-release.yml
- src/Common/Configuration.cs
- src/Garmin/GarminUploader.cs
- src/PelotonToGarminConsole/Program.cs
- src/PelotonToGarminConsole/Startup.cs
> [268] pre-release testing - windows exe

- UnitTests/Conversion/ConverterTests.cs
- src/Conversion/IConverter.cs
> [269] pre-release testing - docker console - fixing unknown unit

- src/Common/Constants.cs
> [263] set release version 3.0.0

- .github/workflows/tag-release.yml
- src/Api/Program.cs
- src/Common/Constants.cs
- src/PelotonToGarminConsole/Startup.cs
- src/WebUI/Program.cs
> [283] always print version and OS information in log file

- UnitTests/Conversion/ConverterTests.cs
- src/Common/Dto/Peloton/UserData.cs
- src/Common/Dto/Peloton/Workout.cs
- src/Common/Observe/Tracing.cs
- src/Conversion/IConverter.cs
- src/Sync/SyncService.cs
> [287] fix Peloton reported FTP

- ReleaseNotes.md
- src/Common/Constants.cs
- src/Common/Database/SettingsDb.cs
> [292] webui - fix 'failed to get settings from db' error on fresh install

- ReleaseNotes.md
- docs/configuration/index.md
- docs/configuration/json.md
- src/Common/Configuration.cs
- src/WebUI/Program.cs
> [298] WebUI - Add configuration support to modify the host and port both the API and WebUI bind to

- ReleaseNotes.md
- src/Api/Controllers/SystemInfoController.cs
- src/WebUI/Pages/Settings.razor
> [295] WebUI - Fix documentation link on settings page was incorrect

- ReleaseNotes.md
- UnitTests/Common/ConfigurationTests.cs
- UnitTests/Sync/SyncServiceTests.cs
- docs/configuration/json.md
- src/Api/Controllers/SyncController.cs
- src/Api/Controllers/SystemInfoController.cs
- src/Common/Configuration.cs
- src/Common/Database/SyncServiceStatus.cs
- src/Garmin/ApiClient.cs
- src/Peloton/ApiClient.cs
- src/Sync/SyncService.cs
> [294] webui - do not make calls to Peloton or Garmin before the user has configured their credentials

- src/Common/Observe/Tracing.cs
- src/Peloton/PelotonService.cs
- src/Sync/SyncService.cs
> [305] fix log message not correct and better error handling when failing to deserialize from Peloton

- ReleaseNotes.md
- UnitTests/AdHocTests.cs
- UnitTests/Data/cycling_workout.json
- src/Common/Constants.cs
- src/Common/Dto/Peloton/UserData.cs
- src/Conversion/IConverter.cs
> [304] Fix Deserialization error when FTP source is `ftp_estimated_source`

- ReleaseNotes.md
- UnitTests/Conversion/ConverterTests.cs
- src/Common/Dto/Unit.cs
- src/Conversion/IConverter.cs
> [309] fix unknown distance unit found for kph and m

- .gitignore
- ReleaseNotes.md
- configuration.example.json
- docker/webui/api.local.json
- docker/webui/webui.local.json
- docs/configuration/index.md
- docs/configuration/json.md
- src/Common/FlurlConfiguration.cs
- src/Garmin/ApiClient.cs
- src/Peloton/ApiClient.cs
> [311] sanitize verbose request logging

- ReleaseNotes.md
- UnitTests/Conversion/ConverterTests.cs
- src/Common/Dto/Peloton/Workout.cs
- src/Conversion/FitConverter.cs
- src/Conversion/IConverter.cs
> [323] fix fire tv workout with missing end time

- ReleaseNotes.md
- UnitTests/Common/FileHandlingTests.cs
- UnitTests/Data/badDeviceInfo.xml
- UnitTests/Data/deviceInfo.xml
- src/Common/FileHandling.cs
> [331] fix async read access to deviceInfo.xml

- ReleaseNotes.md
- UnitTests/AdHocTests.cs
- UnitTests/Conversion/ConverterTests.cs
- UnitTests/Conversion/FitConverterTests.cs
- UnitTests/Sync/SyncServiceTests.cs
- src/Api/Controllers/SettingsController.cs
- src/Api/Controllers/SystemInfoController.cs
- src/Api/Program.cs
- src/Common/Configuration.cs
- src/Common/Http/FlurlConfiguration.cs
- src/Common/Service/FileBasedSettingsService.cs
- src/Common/Service/ISettingsService.cs
- src/Common/Service/SettingsService.cs
- src/Common/Stateful/GarminApiAuthentication.cs
- src/Common/Stateful/IApiAuthentication.cs
- src/Common/Stateful/PelotonApiAuthentication.cs
- src/Conversion/FitConverter.cs
- src/Conversion/IConverter.cs
- src/Conversion/JsonConverter.cs
- src/Conversion/TcxConverter.cs
- src/Garmin/ApiClient.cs
- src/Garmin/Extensions.cs
- src/Garmin/GarminExceptions.cs
- src/Garmin/GarminUploader.cs
- src/Peloton/ApiClient.cs
- src/PelotonToGarminConsole/Program.cs
- src/PelotonToGarminConsole/Startup.cs
- src/Sync/SyncService.cs
- src/WebUI/Program.cs
> [333] Refactor Converters, Settings, Configuration

- ReleaseNotes.md
- docs/install/windows.md
- src/Common/Common.csproj
- src/Common/Http/FlurlConfiguration.cs
- src/Common/Http/PollyHttpClientFactory.cs
- src/Common/Http/PollyPolicies.cs
- src/Conversion/FitConverter.cs
- src/Garmin/GarminUploader.cs
- src/Peloton/PelotonService.cs
- src/PelotonToGarminConsole/PelotonToGarminConsole.csproj.user
- src/Sync/SyncService.cs
- src/UnitTests/AdHocTests.cs
> [343] better support of back-syncing hundreds of workouts

- ReleaseNotes.md
- src/Api/Program.cs
- src/Common/Observe/Tracing.cs
- src/PelotonToGarminConsole/Startup.cs
- src/WebUI/App.razor
- src/WebUI/Pages/About.razor
- src/WebUI/Pages/Index.razor
- src/WebUI/Pages/Settings.razor
- src/WebUI/Pages/Sync.razor
- src/WebUI/Program.cs
- src/WebUI/TracingComponentBase.cs
- src/WebUI/_Imports.razor
> [336] fix opentelemetry tracing in WebUI

- ReleaseNotes.md
- src/Common/Constants.cs
- src/Common/Service/FileBasedSettingsService.cs
- src/PelotonToGarminConsole/Program.cs
> [354] fix Console application failed to convert workout with error: KeyNotFoundException

- ReleaseNotes.md
- src/Common/Configuration.cs
- src/Common/Constants.cs
- src/Conversion/FitConverter.cs
- src/Conversion/IConverter.cs
- src/Conversion/JsonConverter.cs
- src/Conversion/TcxConverter.cs
- src/Peloton/PelotonService.cs
- src/UnitTests/AdHocTests.cs
- src/UnitTests/Common/ConfigurationTests.cs
- src/UnitTests/Conversion/ConverterTests.cs
- src/UnitTests/Conversion/FitConverterTests.cs
- src/UnitTests/Conversion/JsonConverterTests.cs
- src/UnitTests/Conversion/TcxConverterTests.cs
- src/WebUI/Pages/Settings.razor
> [361] fix incorrect conversion format being uploaded to garmin

- ReleaseNotes.md
- src/GitHub/GitHubService.cs
- src/UnitTests/GitHub/GitHubServiceTests.cs
> [353] fix new release check

- ReleaseNotes.md
- images/logo/p2g_penpot.svg
- src/Api/Controllers/PelotonWorkoutsController.cs
- src/Api/Controllers/SyncController.cs
- src/Common/Dto/Api/IPaging.cs
- src/Common/Dto/Api/PelotonWorkoutsRequest.cs
- src/Common/Dto/Api/SyncContracts.cs
- src/Common/Dto/P2GWorkout.cs
- src/Common/Dto/Peloton/Ride.cs
- src/Common/Dto/Peloton/UserData.cs
- src/Common/Dto/Peloton/Workout.cs
- src/Common/Dto/ServiceResult.cs
- src/Common/Dto/WorkoutType.cs
- src/Common/Helpers/Guard.cs
- src/Peloton/ApiClient.cs
- src/Peloton/PelotonService.cs
- src/PelotonToGarminConsole/Startup.cs
- src/Sync/SyncResult.cs
- src/Sync/SyncService.cs
- src/UnitTests/AdHocTests.cs
- src/UnitTests/Api/Controllers/PelotonWorkoutsControllerTests.cs
- src/UnitTests/Api/Controllers/SyncControllerTests.cs
- src/UnitTests/Common/Dto/P2GWorkoutTests.cs
- src/UnitTests/Peloton/PelotonServiceTests.cs
- src/UnitTests/Sync/SyncServiceTests.cs
- src/UnitTests/UnitTestHelpers/Extensions.cs
- src/WebUI/ApiClient.cs
- src/WebUI/Pages/Index.razor
- src/WebUI/Pages/Sync.razor
- src/WebUI/WebUI.csproj
> [26] Support to Upload by date instead of last # activities

- src/Api/Program.cs
- src/Common/Database/DbMigrations.cs
- src/Common/Database/SettingsDb.cs
- src/Common/Database/SyncStatusDb.cs
- src/Common/Database/UsersDb.cs
- src/Common/Dto/P2G/P2GUser.cs
- src/Common/Service/SettingsService.cs
- src/UnitTests/Common/Database/DbMigrationsTests.cs
- vNextReleaseNotes.md
> [399] WebUI - data migration to Admin user

- src/Api/Controllers/SettingsController.cs
- src/Common/Dto/Api/SettingsContracts.cs
- src/Common/Helpers/Guard.cs
- src/UnitTests/Api/Controllers/SettingsControllerTests.cs
- src/WebUI/ApiClient.cs
- src/WebUI/Pages/Settings.razor
- vNextReleaseNotes.md
> [301] webui - improve settings page error handling

- .github/workflows/docker_latest.yml
- .github/workflows/pr-check.yml
- .github/workflows/publish_distros_latest.yml
- .github/workflows/release.yml
- PelotonToGarmin.sln
- docker/Dockerfile.api
- docker/Dockerfile.console
- docker/Dockerfile.webui
- vNextReleaseNotes.md
> [310] add support for arm 32bit images

- src/Common/Common.csproj
- src/PelotonToGarminConsole/PelotonToGarminConsole.csproj
- src/UnitTests/UnitTests.csproj
- src/WebUI/WebUI.csproj
- vNextReleaseNotes.md
> [402] [housekeeping] dependency bumps

- src/Conversion/IConverter.cs
- src/UnitTests/AdHocTests.cs
- src/UnitTests/Conversion/ConverterTests.cs
- vNextReleaseNotes.md
> [414] fix calories missing on Garmin when provided by Apple Watch

- .github/workflows/pr-check.yml
- .github/workflows/publish_distros_latest.yml
- .github/workflows/release.yml
- docker/Dockerfile.api
- docker/Dockerfile.console
- docker/Dockerfile.webui
- docs/install/source.md
- src/Api/Api.csproj
- src/Common/Common.csproj
- src/Common/Constants.cs
- src/Conversion/Conversion.csproj
- src/Garmin/Garmin.csproj
- src/Peloton/Peloton.csproj
- src/PelotonToGarminConsole/PelotonToGarminConsole.csproj
- src/Sync/Sync.csproj
- src/UnitTests/UnitTests.csproj
- src/WebUI/WebUI.csproj
- vNextReleaseNotes.md
> [421] uplift to dotnet 7

- .github/workflows/sync_peloton_to_garmin.yml
- configuration.example.json
- docs/configuration/json.md
- src/Common/Configuration.cs
- src/Garmin/GarminUploader.cs
- src/PelotonToGarminConsole/Startup.cs
- vNextReleaseNotes.md
> [302] remove deprecated settings

- src/Common/Constants.cs
- src/Common/Helpers/WorkoutHelper.cs
- src/Conversion/FitConverter.cs
- src/UnitTests/Common/Helpers/WorkoutHelperTests.cs
- vNextReleaseNotes.md
> [430] fix where error throw when * in workout title

- src/Api/Program.cs
- src/Common/Observe/Logging.cs
- src/Common/Stateful/Statics.cs
- src/PelotonToGarminConsole/Program.cs
- src/WebUI/Program.cs
- vNextReleaseNotes.md
> [438] log config file path on startup

- src/Common/Constants.cs
- src/Common/Dto/Peloton/CompletedMovementsSummaryData.cs
- vNextReleaseNotes.md
> [445] fix: failed to convert body weight strength workout

- src/Peloton/PelotonService.cs
- src/UnitTests/Peloton/PelotonServiceTests.cs
- vNextReleaseNotes.md
> [457] guard against invalid Ride Id e.g "000000"

- src/Common/Dto/P2GWorkout.cs
- src/Common/Dto/Peloton/Segment.cs
- src/Common/Dto/Unit.cs
- src/Conversion/ExerciseMapping.cs
- src/Peloton/P2GWorkoutExerciseMapper.cs
- src/Peloton/PelotonService.cs
- src/UnitTests/Peloton/P2GWorkoutExerciseMapperTests.cs
- vNextReleaseNotes.md
> [453] strength - handle cases where some exercises are missed from the class plan

- src/Api/Program.cs
- src/ClientUI/MauiProgram.cs
- src/Common/ObservabilityStartup.cs
- src/WebUI/Program.cs
> [479] winui remove metrics/tracing support

- src/WebUI/Shared/GarminMfaModal.razor
Update to treat the Mfa code as a string to handle leading zeros.
> [491] Treat Mfa code as a string

- src/Api/Api.csproj
- src/Common/Common.csproj
- src/ConsoleClient/ConsoleClient.csproj
- src/SharedUI/SharedUI.csproj
- src/SharedUI/libman.json
- src/SharedUI/wwwroot/css/site.css
- src/UnitTests/UnitTests.csproj
- src/WebUI/Pages/_Layout.cshtml
> [482][480] cleanup css, fix nav menu highlighting

- src/Common/Constants.cs
- src/Common/Dto/Peloton/Workout.cs
- vNextReleaseNotes.md
> [497] add support for Rowing Bootcamp

- src/Peloton/PelotonService.cs
- src/UnitTests/Data/p2g_workouts/gym_workout.json
- vNextReleaseNotes.md
> [502] partial support for Peloton Gym workouts

- src/Api.Contract/SystemInfoRequest.cs
- src/Api.Service/SystemInfoService.cs
- src/Api/Controllers/SystemInfoController.cs
- src/ClientUI/ServiceClient.cs
- src/Common/Common.csproj
- src/Common/ObservabilityStartup.cs
- src/Common/Observe/Logging.cs
- src/SharedUI/IApiClient.cs
- src/SharedUI/Pages/About.razor
- src/SharedUI/Shared/Logs.razor
- src/SharedUI/Shared/SystemInfo.razor
- src/WebUI/ApiClient.cs
> [486] support viewing logs from UI

- .github/workflows/sync_peloton_to_garmin.yml
Fixes #534 
Continuation of #535
> 534: Zip files before uploading

- docs/install/github-action.md
- src/Common/Constants.cs
- src/Conversion/ExerciseMapping.cs
- src/Garmin/Auth/GarminAuthenticationService.cs
- vNextReleaseNotes.md
closes #541 
closes #546
closes #547
> [541] fix garmin MFA flow

- mkdocs/docs/configuration/json.md
- src/Common/Dto/P2GWorkout.cs
- src/Common/Dto/WorkoutType.cs
- src/UnitTests/Common/Dto/P2GWorkoutTests.cs
- src/UnitTests/Sync/SyncServiceTests.cs
- vNextReleaseNotes.md
> [559] feat: add option to exclude Outdoor Cycling workouts

- src/Api.Service/Api.Service.csproj
- src/Api.Service/ApiStartupServices.cs
- src/Api.Service/SystemInfoService.cs
- src/Api.Service/VersionInformationService.cs
- src/SharedUI/Pages/Settings.razor
- src/UnitTests/Api.Service/SystemInfoServiceTests.cs
- vNextReleaseNotes.md
> [581] fix: Fix broken Documentation link in UI

- src/Peloton/AnnualChallenge/AnnualChallengeService.cs
- src/SharedUI/Pages/AnnualChallengeProgress.razor
- vNextReleaseNotes.md
> [588] fix: annual challenge page (and maybe more resilient for next year)

- images/P2G_diagram.drawio
- mkdocs/docs/configuration/json.md
- src/Common/Common.csproj
- src/Common/Constants.cs
- src/Common/Dto/P2GWorkout.cs
- src/Common/Dto/Settings.cs
- src/Common/Helpers/WorkoutHelper.cs
- src/Conversion/FitConverter.cs
- src/SharedUI/Shared/FormatSettingsForm.razor
- src/SharedUI/wwwroot/css/site.css
- src/UnitTests/Common/Helpers/WorkoutHelperTests.cs
- vNextReleaseNotes.md
> [591] feat: garmin workout title templating support

- src/Api.Contract/PelotonAnnualChallengeContracts.cs
- src/Api.Service/ApiStartupServices.cs
- src/Api.Service/Mappers/AnnualChallengeMapper.cs
- src/Api.Service/PelotonAnnualChallengeService.cs
- src/Api/Controllers/PelotonAnnualChallengeController.cs
- src/ClientUI/ServiceClient.cs
- src/Peloton/AnnualChallenge/AnnualChallengeProgress.cs
- src/Peloton/AnnualChallenge/AnnualChallengeService.cs
- src/SharedUI/Pages/AnnualChallengeProgress.razor
- vNextReleaseNotes.md
closes #600 
Also took this opportunity to de-dupe the Annual Challenge code and refactor to new Api.Service pattern.
> [600] feat: calculate how many minutes you will need per day/week in order to meet the goal by the end of the year

- .github/actions/publish-ui-dist/action.yaml
- .github/workflows/publish-release.yaml
- src/Common/Dto/Settings.cs
> [572] bug: try fix release workflow

- src/Common/Constants.cs
- src/Common/Helpers/WorkoutHelper.cs
- src/UnitTests/Common/Helpers/WorkoutHelperTests.cs
- vNextReleaseNotes.md
> [604] fix: workout title template not handling special characters correctly

- src/Api.Contract/PelotonWorkoutsRequest.cs
- src/Conversion/IConverter.cs
- src/Peloton/ApiClient.cs
- src/SharedUI/Pages/Sync.razor
- src/SharedUI/Shared/AppSettingsForm.razor
- vNextReleaseNotes.md
> [610]  feat: add more workout details to Sync page

- mkdocs/docs/configuration/json.md
Add requirements for custom titles to take effect
> Docs: Workout Title Templating note

- PelotonToGarmin.sln
- src/Api.Service/ApiStartupServices.cs
- src/Api.Service/BackgroundSyncJob.cs
- vNextReleaseNotes.md
> [634] fix: periodic sync not working on webui

- src/Common/Dto/Peloton/Summary.cs
- src/Conversion/FitConverter.cs
- src/UnitTests/AdHocTests.cs
- vNextReleaseNotes.md
> [476] feat: sync tread total ascent/elevation to FIT file

- src/Peloton/AnnualChallenge/AnnualChallengeService.cs
Update Annual Challange to 2025
> Peloton Annual Challenge - 2025

- src/Api.Contract/SettingsContracts.cs
- src/Api.Service/SettingsUpdaterService.cs
- src/Api/Controllers/PelotonWorkoutsController.cs
- src/ClientUI/ClientUI.csproj
- src/ClientUI/ServiceClient.cs
- src/Common/Constants.cs
- src/Common/Database/UsersDb.cs
- src/Common/Http/PollyPolicies.cs
- src/SharedUI/Pages/AnnualChallengeProgress.razor
- src/SharedUI/Pages/Index.razor
- src/SharedUI/Pages/Sync.razor
- src/SharedUI/Shared/GarminSettingsForm.razor
- src/SharedUI/Shared/PelotonSettingsForm.razor
- src/SharedUI/SharedUI.csproj
- src/UnitTests/Api.Service/SettingsUpdaterServiceTests.cs
- vNextReleaseNotes.md
> [711] Misc Polish and UX improvements

- mkdocs/docs/migration/migrate-v4-v5.md
- src/Api.Service/SettingsUpdaterService.cs
- src/Common/Database/DbMigrations.cs
- src/Common/Database/SettingsDb.cs
- src/Common/Dto/Settings.cs
- src/Common/Service/FileBasedSettingsService.cs
- src/Common/Service/SettingsService.cs
- src/SharedUI/Shared/FormatSettingsForm.razor
- src/UnitTests/Api.Service/SettingsUpdaterServiceTests.cs
- src/UnitTests/Common/ConfigurationTests.cs
- src/UnitTests/Common/Database/DbMigrationsTests.cs
- src/UnitTests/Common/Service/SettingServiceTests.cs
- vNextReleaseNotes.md
> [704] remove obsolete DeviceInfoPath from settings

- src/ClientUI/ClientUI.csproj
> [707] attemp fix ClientUI GH build

- src/Api.Contract/PelotonAnnualChallengeContracts.cs
- src/Api.Service/PelotonAnnualChallengeService.cs
- src/Peloton/AnnualChallenge/AnnualChallengeProgress.cs
- src/Peloton/AnnualChallenge/AnnualChallengeService.cs
- src/SharedUI/Pages/AnnualChallengeProgress.razor
- vNextReleaseNotes.md
> [724] feat: show current pace on Annual Challenge page

- src/Api.Contract/SyncContracts.cs
- src/Api.Service/BackgroundSyncJob.cs
- src/Api.Service/Validators/SyncValidators.cs
- src/Api/Controllers/SyncController.cs
- src/ConsoleClient/Startup.cs
- src/Sync/SyncService.cs
- vNextReleaseNotes.md
> [697] feat: new API endpoint to sync last N workouts

- .github/workflows/sync_peloton_to_garmin.yml
- mkdocs/docs/configuration/app.md
- src/Common/Dto/Settings.cs
- src/ConsoleClient/Startup.cs
- vNextReleaseNotes.md
> [740] feat: configure whether console app should exit immediately
